// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using Huanlin.Braille;
using Huanlin.Braille.Converters;

namespace Huanlin.Braille.UnitTest
{
    /// <summary>
    ///This is a test class for Huanlin.Braille.EnglishWordConverter and is intended
    ///to contain all Huanlin.Braille.EnglishWordConverter Unit Tests
    ///</summary>
    [TestClass()]
    public class EnglishWordConverterTest
    {


        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion


        /// <summary>
        ///A test for Convert (Stack&lt;char&gt;)
        ///</summary>
        [TestMethod()]
        public void ConvertTest()
        {
            string msg = "EnglishWordConverter.Convert 測試失敗: ";

            EnglishWordConverter target = new EnglishWordConverter();

			ContextTagManager context = new ContextTagManager();

            // 測試刪節號。
            string text = "...";
            Stack<char> charStack = new Stack<char>(text);
            List<BrailleWord> expected = new List<BrailleWord>();
            BrailleWord brWord = new BrailleWord(text, "040404");
            expected.Add(brWord);
            List<BrailleWord> actual = target.Convert(charStack, context);
            CollectionAssert.AreEqual(expected, actual, msg + text);
            charStack.Clear();

            // 測試左單引號。
            text = "‘";
            charStack = new Stack<char>(text);
            brWord = new BrailleWord(text, "2026");
            expected.Clear();
            expected.Add(brWord);
            actual = target.Convert(charStack, context);
            CollectionAssert.AreEqual(expected, actual, msg + text);
            charStack.Clear();

            // 測試左雙引號。
            text = "“";
            charStack = new Stack<char>(text);
            brWord = new BrailleWord(text, "26");
            expected.Clear();
            expected.Add(brWord);
            actual = target.Convert(charStack, context);
            CollectionAssert.AreEqual(expected, actual, msg + text);
            charStack.Clear();

            // 測試大寫字母（不用加大寫記號，因為延後到整行調整時才處理）。
            text = "A";
            charStack = new Stack<char>(text);
            brWord = new BrailleWord(text, "01");
            expected.Clear();
            expected.Add(brWord);
            actual = target.Convert(charStack, context);
            CollectionAssert.AreEqual(expected, actual, msg + text);
            charStack.Clear();  
          
            // 測試數字
            text = "6";
            charStack = new Stack<char>(text);
            brWord = new BrailleWord(text, "16");	// 下位點。
            expected.Clear();
            expected.Add(brWord);
            actual = target.Convert(charStack, context);
            CollectionAssert.AreEqual(expected, actual, msg + text);
            charStack.Clear();            
        }
    }
}
