skip_non_tags: false
pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2022
configuration: Release

environment:
  fast_finish: true  # set this flag to immediately finish build once one of the jobs fails.
  solution_name: HuanlinLib.sln

before_build:
- cmd: dotnet restore %solution_name%

build:
  project: '%solution_name%'

  # MSBuild verbosity level
  verbosity: minimal

after_build:
  - dotnet pack src\Huanlin.Common\Huanlin.Common.csproj
  - dotnet pack src\Huanlin.AppBlock\Huanlin.AppBlock.csproj
  - dotnet pack src\Huanlin.Windows\Huanlin.Windows.csproj

deploy:
  - provider: NuGet
    api_key:
      secure: F+FEV17LBxIXlSSCC5LD2P9rhkpjGzzD34LaalIJRCSW+8mM9YeI08i9WU/0ZojP
    on:
      APPVEYOR_REPO_TAG: true
    artifact: /.*(\.|\.s)nupkg/

artifacts:
- path: output\**\*.nupkg