// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Huanlin.Common.Helpers;
using NUnit.Framework;

namespace Test.Huanlin
{
    /// <summary>
    ///This is a test class for Huanlin.Common.Helpers.StrHelper and is intended
    ///to contain all Huanlin.Common.Helpers.StrHelper Unit Tests
    ///</summary>
    [TestFixture]
    public class StrHelperTest
    {
        /// <summary>
        ///A test for IsEmpty (string)
        ///</summary>
        [Test]
        public void IsEmptyTest()
        {
            string input = " \t　\r\n";

            bool expected = true;
            bool actual = StrHelper.IsEmpty(input);

            Assert.That(actual, Is.EqualTo(expected), "global::Huanlin.Text.StrHelper.IsEmpty did not return the expected value.");
        }

        /// <summary>
        ///A test for RemoveSpaces (string, bool)
        ///</summary>
        [Test]
        public void RemoveSpacesTest()
        {
            string input = "a b　c";
            bool fullShapeSpaces = true;

            string expected = "abc";
            string actual;

            actual = StrHelper.RemoveSpaces(input, fullShapeSpaces);

            Assert.That(actual, Is.EqualTo(expected), "global::Huanlin.Text.StrHelper.RemoveSpaces did not return the expected value.");
        }

        /// <summary>
        ///A test for FullShapeSpaceToSpace (string)
        ///</summary>
        [Test]
        public void FullShapeSpaceToSpaceTest()
        {
            string input = "a　b";

            string expected = "a b";
            string actual;

            actual = StrHelper.FullShapeSpaceToSpace(input);

            Assert.That(actual, Is.EqualTo(expected), "global::Huanlin.Text.StrHelper.FullShapeSpaceToSpace did not return the expected value.");
        }
    }


}
