// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Test.Huanlin
{
    /// <summary>
    ///This is a test class for Huanlin.Helpers.ByteHelper and is intended
    ///to contain all Huanlin.Helpers.ByteHelper Unit Tests
    ///</summary>
    [TestClass()]
	public class ByteHelperTest
	{


		private TestContext testContextInstance;

		/// <summary>
		///Gets or sets the test context which provides
		///information about and functionality for the current test run.
		///</summary>
		public TestContext TestContext
		{
			get
			{
				return testContextInstance;
			}
			set
			{
				testContextInstance = value;
			}
		}
		#region Additional test attributes
		// 
		//You can use the following additional attributes as you write your tests:
		//
		//Use ClassInitialize to run code before running the first test in the class
		//
		//[ClassInitialize()]
		//public static void MyClassInitialize(TestContext testContext)
		//{
		//}
		//
		//Use ClassCleanup to run code after all tests in a class have run
		//
		//[ClassCleanup()]
		//public static void MyClassCleanup()
		//{
		//}
		//
		//Use TestInitialize to run code before running each test
		//
		//[TestInitialize()]
		//public void MyTestInitialize()
		//{
		//}
		//
		//Use TestCleanup to run code after each test has run
		//
		//[TestCleanup()]
		//public void MyTestCleanup()
		//{
		//}
		//
		#endregion


		/// <summary>
		///A test for Reverse (byte)
		///</summary>
		[TestMethod()]
		public void ReverseTest()
		{
			byte aByte = 0xb8;
			byte expected = 0x1d;
			byte actual = global::Huanlin.Helpers.ByteHelper.Reverse(aByte);
			Assert.AreEqual(expected, actual, "Huanlin.Helpers.ByteHelper.Reverse 測試失敗!");

			aByte = 0x93;
			expected = 0xc9;
			actual = global::Huanlin.Helpers.ByteHelper.Reverse(aByte);
			Assert.AreEqual(expected, actual, "Huanlin.Helpers.ByteHelper.Reverse 測試失敗!");
		}

	}


}
